version: "3"

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=production
      - FLASK_RUN_PORT=5000

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/builds/root/task-manager-usin-flask/prometheus/prometheus.yml
      - ./alert.rules.yml:/builds/root/task-manager-usin-flask/prometheus/alert.rules.yml
    command:
      - "--config.file=/builds/root/task-manager-usin-flask/prometheus/prometheus.yml"
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana_data:/var/lib/grafana

volumes:
  grafana_data:
